[workspace]

members = [
    "voxel_test",
    "voxel_engine",
    "voxel_render",
    "voxel_shared",
]


#nivel de optimisacion 0-3
# 0 > sin optimisacion (25fps aprox)
# 1 > (60fps)
[profile.dev]
opt-level = 2
